The table summarizes the GORM modules and the dependencies you should add to your build to enable them.

.Data Access Configuration Modules
|===
|Dependency|Description

|`io.micronaut.groovy:micronaut-hibernate-gorm`
|Configures http://gorm.grails.org/latest/hibernate/manual[GORM for Hibernate] for Groovy applications

|`io.micronaut.groovy:micronaut-mongo-gorm`
|Configures http://gorm.grails.org/latest/mongodb/manual[GORM for MongoDB] for Groovy applications

|`io.micronaut.groovy:micronaut-neo4j-gorm`
|Configures http://gorm.grails.org/latest/neo4j/manual[GORM for Neo4j] for Groovy applications

|===

== Using GORM for Hibernate

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `hibernate-gorm` feature to include GORM, a basic connection pool configuration, and a default H2 database driver in your project:
----
$ mn create-app my-app --features hibernate-gorm
----
====

For Groovy users and users familiar with the Grails framework, special support for http://gorm.grails.org[GORM for Hibernate] is available. To use GORM for Hibernate you *should not* include Micronaut's built in <<sqlSupport, SQL Support>> or the `hibernate-jpa` dependency since GORM itself takes responsibility for creating the `DataSource`, `SessionFactory` etc.

Rather, you only need to include the  `hibernate-gorm` dependency in your project, a connection pool implementation, and the desired JDBC driver. For example:

dependency:micronaut-hibernate-gorm[groupId="io.micronaut.groovy"]

You will likely want to add a connection pool implementation and potentially the `h2` database for in-memory testing:

.Configuring GORM for Hibernate
[source,groovy]
----
  // Use Tomcat connection pool
  runtime 'org.apache.tomcat:tomcat-jdbc'
  // Use H2 database driver
  runtime  'com.h2database:h2'
----

You can now use the same http://gorm.grails.org/latest/hibernate/manual/index.html#configuration[configuration properties described in the GORM documentation]. For example:

.Configuring GORM for Hibernate
[configuration]
----
dataSource:
    pooled: true
    dbCreate: create-drop
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password:
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
----

The following should be noted regarding using GORM for Hibernate in Micronaut:

* Each class you wish to be a GORM entity should be annotated with the `grails.gorm.annotation.Entity` annotation.
* Each method that interacts with GORM should be annotated with GORM's `grails.gorm.transactions.Transactional` to ensure a session is present. You can also add the `@Transactional` annotation to the class.
* By default Micronaut will scan for entities relative to your `Application` class. If you wish to customize this specify additional packages via the https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContextBuilder.html[ApplicationContextBuilder] when starting your application.

=== Package scan

For example, if all your GORM entities are in the package `example.micronaut.entities`.

Instead of:

[source,groovy]
----
import io.micronaut.runtime.Micronaut
import groovy.transform.CompileStatic

@CompileStatic
class Application {
    static void main(String[] args) {
        Micronaut.run(Application)
    }
}
----

Use:

[source,groovy]
----
import io.micronaut.runtime.Micronaut
import groovy.transform.CompileStatic

@CompileStatic
class Application {
    static void main(String[] args) {
        Micronaut.build(args)
                .packages("example.micronaut.entities")
                .mainClass(Application.class)
                .start()
    }
}
----

In tests, where you start manually an `ApplicationContext`, use:

[source, groovy]
----
class BookServiceSpec extends Specification {

    @AutoCleanup
    @Shared
    ApplicationContext applicationContext = ApplicationContext.build()
            .packages("example.micronaut.entities")
            .build()
            .start()

    @Shared
    @Subject
    BookService bookService = applicationContext.getBean(BookService)
----

In tests, where you use `@MicronautTest`, use:

[source, groovy]
----
@MicronautTest(packages = "example.micronaut.entities")
class MicronautTestBookServiceSpec extends Specification {

    @Inject
    BookService bookService

----

== Using GORM for MongoDB

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `mongo-gorm` feature to configure GORM for MongoDB in your project:
----
$ mn create-app my-app --features mongo-gorm
----
====

For Groovy users and users familiar with Grails, special support has been added to Micronaut for using http://gorm.grails.org/latest/mongodb/manual[GORM for MongoDB].

To add support for GORM for MongoDB, first configure the MongoDB connection as per instructions earlier in the guide, then add the following dependency to your application:

dependency:micronaut-mongo-gorm[groupId="io.micronaut.groovy"]

WARNING: For GORM for MongoDB you will need to configure the database name separately as the `grails.mongodb.datataseName` property in the application configuration file.

The following should be noted regarding using GORM for MongoDB in Micronaut:

* Each class you wish to be a GORM entity should be annotated with the `grails.gorm.annotation.Entity` annotation.
* Each method that interacts with GORM should be annotated with GORM's `grails.gorm.transactions.Transactional` to ensure a session is present. You can also add the `@Transactional` annotation to the class.
* By default Micronaut will scan for entities relative to your `Application` class. If you wish to customize this specify additional packages via the https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContextBuilder.html[ApplicationContextBuilder] when starting your application.

== Using GORM for Neo4j

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `neo4j-gorm` feature to configure GORM for Neo4j in your project:
----
$ mn create-app my-app --features neo4j-gorm
----
====

For Groovy users and users familiar with Grails, special support has been added to Micronaut for using http://gorm.grails.org/latest/neo4j/manual[GORM for Neo4j].

To add support for GORM for Neo4j, first configure the Neo4j connection as per instructions earlier in the guide, then add the following dependency to your application:

dependency:micronaut-neo4j-gorm[groupId="io.micronaut.groovy"]

The following should be noted regarding using GORM for Neo4j in Micronaut:

* Each class you wish to be a GORM entity should be annotated with the `grails.gorm.annotation.Entity` annotation.
* Each method that interacts with GORM should be annotated with GORM's `grails.gorm.transactions.Transactional` to ensure a session is present. You can also add the `@Transactional` annotation to the class.
* By default Micronaut will scan for entities relative to your `Application` class. If you wish to customize this specify additional packages via the api:context.ApplicationContextBuilder[] when starting your application.
