plugins {
    id 'io.micronaut.build.internal.groovy-module'
}

dependencies {
    api mn.groovy

    implementation mn.micronaut.inject
    implementation("io.micronaut:micronaut-module-info:5.0.0-M6")
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.groovy:micronaut-runtime-groovy"
    }
}
